language: python

python:
  - "pypy"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --use-mirrors coveralls 
  - python setup.py install

script:
  - python setup.py nosetests

after_success:
  - coveralls
